using System;
using System.Collections.Generic;
using Assets.Scripts.Localization2;
using Assets.Scripts.Networking;
using Assets.Scripts.Objects.Electrical;
using Assets.Scripts.Objects.Pipes;
using UnityEngine.Networking;

namespace Assets.Scripts.Objects.Motherboards;

public class LogicBase : IRocketReaderWriter
{
	public Device Device;

	public static List<ScriptCommand> DeprecatedCommands = new List<ScriptCommand>
	{
		ScriptCommand.label,
		ScriptCommand.getd,
		ScriptCommand.putd,
		ScriptCommand.ld,
		ScriptCommand.sd
	};

	public static List<LogicSlotType> DeprecatedSlotTypes = new List<LogicSlotType>();

	public static List<LogicType> Deprecated = new List<LogicType>
	{
		LogicType.None,
		LogicType.ImportQuantity,
		LogicType.ImportSlotOccupant,
		LogicType.ExportQuantity,
		LogicType.ExportSlotOccupant,
		LogicType.ExportSlotHash,
		LogicType.ImportSlotHash,
		LogicType.PlantHealth1,
		LogicType.PlantHealth2,
		LogicType.PlantHealth3,
		LogicType.PlantHealth4,
		LogicType.PlantGrowth1,
		LogicType.PlantGrowth2,
		LogicType.PlantGrowth3,
		LogicType.PlantGrowth4,
		LogicType.PlantEfficiency1,
		LogicType.PlantEfficiency2,
		LogicType.PlantEfficiency3,
		LogicType.PlantEfficiency4,
		LogicType.PlantHash1,
		LogicType.PlantHash2,
		LogicType.PlantHash3,
		LogicType.PlantHash4
	};

	public static bool IsDeprecated(LogicType logicType)
	{
		if (Deprecated.Contains(logicType))
		{
			return true;
		}
		return false;
	}

	public static bool IsDeprecated(LogicSlotType logicType)
	{
		if (DeprecatedSlotTypes.Contains(logicType))
		{
			return true;
		}
		return false;
	}

	public static bool IsDeprecated(ScriptCommand command)
	{
		if (DeprecatedCommands.Contains(command))
		{
			return true;
		}
		return false;
	}

	public static string GetLogicDescription(LogicSlotType logicSlotType)
	{
		return logicSlotType switch
		{
			LogicSlotType.None => InterfaceStrings.LogicSlotTypeNone, 
			LogicSlotType.ReferenceId => GameStrings.LogicDescriptionReferenceId.DisplayString, 
			LogicSlotType.Occupied => InterfaceStrings.LogicSlotTypeOccupied, 
			LogicSlotType.OccupantHash => InterfaceStrings.LogicSlotTypeOccupantHash, 
			LogicSlotType.Quantity => InterfaceStrings.LogicSlotTypeQuantity, 
			LogicSlotType.Damage => InterfaceStrings.LogicSlotTypeDamage, 
			LogicSlotType.Efficiency => InterfaceStrings.LogicSlotTypeEfficiency, 
			LogicSlotType.Mature => InterfaceStrings.LogicSlotTypeMature, 
			LogicSlotType.Health => InterfaceStrings.LogicSlotTypeHealth, 
			LogicSlotType.Growth => InterfaceStrings.LogicSlotTypeGrowth, 
			LogicSlotType.Pressure => InterfaceStrings.LogicSlotTypePressure, 
			LogicSlotType.Temperature => InterfaceStrings.LogicSlotTypeTemperature, 
			LogicSlotType.Charge => InterfaceStrings.LogicSlotTypeCharge, 
			LogicSlotType.ChargeRatio => InterfaceStrings.LogicSlotTypeChargeRatio, 
			LogicSlotType.Class => InterfaceStrings.LogicSlotTypeClass, 
			LogicSlotType.PressureWaste => InterfaceStrings.LogicSlotTypePressureWaste, 
			LogicSlotType.PressureAir => InterfaceStrings.LogicSlotTypePressureAir, 
			LogicSlotType.MaxQuantity => InterfaceStrings.LogicSlotTypeMaxQuantity, 
			LogicSlotType.PrefabHash => InterfaceStrings.LogicSlotTypePrefabHash, 
			LogicSlotType.Seeding => InterfaceStrings.LogicSlotTypeSeeding, 
			LogicSlotType.LineNumber => InterfaceStrings.LogicTypeLineNumber, 
			LogicSlotType.MaturityRatio => GameStrings.LogicDescriptionMaturityRatio.DisplayString, 
			LogicSlotType.SeedingRatio => GameStrings.LogicDescriptionSeedingRatio.DisplayString, 
			LogicSlotType.FreeSlots => GameStrings.LogicDescriptionFreeSlots.DisplayString, 
			LogicSlotType.TotalSlots => GameStrings.LogicDescriptionTotalSlots.DisplayString, 
			_ => InterfaceStrings.LogicTypeUnknown, 
		};
	}

	public static string GetLogicDescription(LogicType logicType)
	{
		return logicType switch
		{
			LogicType.TotalQuantity => GameStrings.LogicDescriptionTotalQuantity, 
			LogicType.MinedQuantity => GameStrings.LogicDescriptionMinedQuantity, 
			LogicType.Density => GameStrings.LogicDescriptionDensity, 
			LogicType.Richness => GameStrings.LogicDescriptionRichness, 
			LogicType.Size => GameStrings.LogicDescriptionSize, 
			LogicType.CurrentCode => GameStrings.LogicDescriptionCurrentCode.DisplayString, 
			LogicType.DestinationCode => GameStrings.LogicDescriptionDestinationCode.DisplayString, 
			LogicType.Discover => GameStrings.LogicDescriptionDiscover.DisplayString, 
			LogicType.Chart => GameStrings.LogicDescriptionChart.DisplayString, 
			LogicType.Survey => GameStrings.LogicDescriptionSurvey.DisplayString, 
			LogicType.NavPoints => GameStrings.LogicDescriptionNavPoints.DisplayString, 
			LogicType.ChartedNavPoints => GameStrings.LogicDescriptionChartedNavPoints.DisplayString, 
			LogicType.Sites => GameStrings.LogicDescriptionSites.DisplayString, 
			LogicType.SemiMajorAxis => GameStrings.LogicDescriptionSemiMajorAxis.DisplayString, 
			LogicType.Eccentricity => GameStrings.LogicDescriptionEccentricity.DisplayString, 
			LogicType.Inclination => GameStrings.LogicDescriptionInclination.DisplayString, 
			LogicType.OrbitPeriod => GameStrings.LogicDescriptionPeriod.DisplayString, 
			LogicType.HealthDamage => GameStrings.LogicDescriptionHealthDamage.DisplayString, 
			LogicType.StunDamage => GameStrings.LogicDescriptionStunDamage.DisplayString, 
			LogicType.DistanceAu => GameStrings.LogicDescriptionDistanceAu.DisplayString, 
			LogicType.DistanceKm => GameStrings.LogicDescriptionDistanceKm.DisplayString, 
			LogicType.CelestialParentHash => GameStrings.LogicDescriptionCelestialParentHash.DisplayString, 
			LogicType.TrueAnomaly => GameStrings.LogicDescriptionTrueAnomaly.DisplayString, 
			LogicType.AlignmentError => GameStrings.LogicDescriptionAlignmentError.DisplayString, 
			LogicType.Index => GameStrings.LogicDescriptionIndex.DisplayString, 
			LogicType.DrillCondition => GameStrings.LogicDescriptionDrillCondition.DisplayString, 
			LogicType.EntityState => GameStrings.LogicDescriptionEntityState.DisplayString, 
			LogicType.Apex => GameStrings.LogicDescriptionApex.DisplayString, 
			LogicType.ReEntryAltitude => GameStrings.ReEntryAltitudeDescription.DisplayString, 
			LogicType.Altitude => GameStrings.AltitudeDescription.DisplayString, 
			LogicType.Gravity => GameStrings.GravityDescription.DisplayString, 
			LogicType.NetworkFault => GameStrings.NetworkFaultDescription.DisplayString, 
			LogicType.ProportionalGain => GameStrings.ProportionalGainDescription.DisplayString, 
			LogicType.IntegralGain => GameStrings.IntegralGainDescription.DisplayString, 
			LogicType.DerivativeGain => GameStrings.DerivativeGainDescription.DisplayString, 
			LogicType.Reset => GameStrings.ResetDescription.DisplayString, 
			LogicType.Setpoint => GameStrings.SetpointDescription.DisplayString, 
			LogicType.Minimum => GameStrings.MinimumDescription.DisplayString, 
			LogicType.FlightControlRule => GameStrings.FlightControlRuleDescription.DisplayString, 
			LogicType.ExhaustVelocity => GameStrings.ExhaustVelocityDescription.DisplayString, 
			LogicType.PassedMoles => GameStrings.PassedMolesDescription.DisplayString, 
			LogicType.Orientation => GameStrings.LogicDescriptionOrientation.DisplayString, 
			LogicType.VelocityX => GameStrings.LogicDescriptionVelocityX.DisplayString, 
			LogicType.VelocityY => GameStrings.LogicDescriptionVelocityY.DisplayString, 
			LogicType.VelocityZ => GameStrings.LogicDescriptionVelocityZ.DisplayString, 
			LogicType.ForwardX => GameStrings.LogicDescriptionForward.DisplayString, 
			LogicType.ForwardY => GameStrings.LogicDescriptionForward.DisplayString, 
			LogicType.ForwardZ => GameStrings.LogicDescriptionForward.DisplayString, 
			LogicType.ReferenceId => GameStrings.LogicDescriptionReferenceId.DisplayString, 
			LogicType.Dispense => GameStrings.LogicDescriptionDispense.DisplayString, 
			LogicType.DispenseSlot => GameStrings.LogicDescriptionDispenseSlot.DisplayString, 
			LogicType.None => InterfaceStrings.LogicTypeNone, 
			LogicType.Power => InterfaceStrings.LogicTypePower, 
			LogicType.Open => InterfaceStrings.LogicTypeOpen, 
			LogicType.Mode => InterfaceStrings.LogicTypeMode, 
			LogicType.Error => InterfaceStrings.LogicTypeError, 
			LogicType.Lock => InterfaceStrings.LogicTypeLock, 
			LogicType.Pressure => InterfaceStrings.LogicTypePressure, 
			LogicType.Temperature => InterfaceStrings.LogicTypeTemperature, 
			LogicType.PressureExternal => InterfaceStrings.LogicTypePressureExternal, 
			LogicType.PressureInternal => InterfaceStrings.LogicTypePressureInternal, 
			LogicType.Activate => InterfaceStrings.LogicTypeActivate, 
			LogicType.Charge => InterfaceStrings.LogicTypeCharge, 
			LogicType.Setting => InterfaceStrings.LogicTypeSetting, 
			LogicType.Reagents => InterfaceStrings.LogicTypeReagents, 
			LogicType.RatioOxygen => InterfaceStrings.LogicTypeRatioOxygen, 
			LogicType.RatioCarbonDioxide => InterfaceStrings.LogicTypeRatioCarbonDioxide, 
			LogicType.RatioNitrogen => InterfaceStrings.LogicTypeRatioNitrogen, 
			LogicType.RatioPollutant => InterfaceStrings.LogicTypeRatioPollutant, 
			LogicType.RatioMethane => InterfaceStrings.LogicTypeRatioMethane, 
			LogicType.RatioWater => InterfaceStrings.LogicTypeRatioWater, 
			LogicType.Combustion => InterfaceStrings.LogicTypeCombustion, 
			LogicType.RatioNitrousOxide => InterfaceStrings.LogicTypeRatioNitrousOxide, 
			LogicType.RatioLiquidNitrogen => InterfaceStrings.LogicTypeRatioLiquidNitrogen, 
			LogicType.Horizontal => InterfaceStrings.LogicTypeHorizontal, 
			LogicType.Vertical => InterfaceStrings.LogicTypeVertical, 
			LogicType.SolarIrradiance => InterfaceStrings.LogicTypeSolarIrradiance, 
			LogicType.SolarAngle => InterfaceStrings.LogicTypeSolarAngle, 
			LogicType.Maximum => InterfaceStrings.LogicTypeMaximum, 
			LogicType.Ratio => InterfaceStrings.LogicTypeRatio, 
			LogicType.PowerPotential => InterfaceStrings.LogicTypePowerPotential, 
			LogicType.PowerActual => InterfaceStrings.LogicTypePowerActual, 
			LogicType.Quantity => InterfaceStrings.LogicTypeQuantity, 
			LogicType.On => InterfaceStrings.LogicTypeOn, 
			LogicType.ImportQuantity => InterfaceStrings.LogicTypeImportQuantity, 
			LogicType.ImportSlotOccupant => InterfaceStrings.LogicTypeImportSlotOccupant, 
			LogicType.ExportQuantity => InterfaceStrings.LogicTypeExportQuantity, 
			LogicType.ExportSlotOccupant => InterfaceStrings.LogicTypeExportSlotOccupant, 
			LogicType.RequiredPower => InterfaceStrings.LogicTypeRequiredPower, 
			LogicType.HorizontalRatio => InterfaceStrings.LogicTypeHorizontalRatio, 
			LogicType.VerticalRatio => InterfaceStrings.LogicTypeVerticalRatio, 
			LogicType.PowerRequired => InterfaceStrings.LogicTypePowerRequired, 
			LogicType.Idle => InterfaceStrings.LogicTypeIdle, 
			LogicType.Color => InterfaceStrings.LogicTypeColor, 
			LogicType.ElevatorSpeed => InterfaceStrings.LogicTypeElevatorSpeed, 
			LogicType.ElevatorLevel => InterfaceStrings.LogicTypeElevatorLevel, 
			LogicType.RecipeHash => InterfaceStrings.LogicTypeRecipeHash, 
			LogicType.ExportSlotHash => InterfaceStrings.LogicTypeExportSlotHash, 
			LogicType.ImportSlotHash => InterfaceStrings.LogicTypeImportSlotHash, 
			LogicType.PlantHealth1 => InterfaceStrings.LogicTypePlantHealth1, 
			LogicType.PlantHealth2 => InterfaceStrings.LogicTypePlantHealth2, 
			LogicType.PlantHealth3 => InterfaceStrings.LogicTypePlantHealth3, 
			LogicType.PlantHealth4 => InterfaceStrings.LogicTypePlantHealth4, 
			LogicType.PlantGrowth1 => InterfaceStrings.LogicTypePlantGrowth1, 
			LogicType.PlantGrowth2 => InterfaceStrings.LogicTypePlantGrowth2, 
			LogicType.PlantGrowth3 => InterfaceStrings.LogicTypePlantGrowth3, 
			LogicType.PlantGrowth4 => InterfaceStrings.LogicTypePlantGrowth4, 
			LogicType.PlantEfficiency1 => InterfaceStrings.LogicTypePlantEfficiency1, 
			LogicType.PlantEfficiency2 => InterfaceStrings.LogicTypePlantEfficiency2, 
			LogicType.PlantEfficiency3 => InterfaceStrings.LogicTypePlantEfficiency3, 
			LogicType.PlantEfficiency4 => InterfaceStrings.LogicTypePlantEfficiency4, 
			LogicType.PlantHash1 => InterfaceStrings.LogicTypePlantHash1, 
			LogicType.PlantHash2 => InterfaceStrings.LogicTypePlantHash2, 
			LogicType.PlantHash3 => InterfaceStrings.LogicTypePlantHash3, 
			LogicType.PlantHash4 => InterfaceStrings.LogicTypePlantHash4, 
			LogicType.RequestHash => InterfaceStrings.LogicTypeRequestHash, 
			LogicType.CompletionRatio => InterfaceStrings.LogicTypeCompletionRatio, 
			LogicType.ClearMemory => InterfaceStrings.LogicTypeClearMemory, 
			LogicType.ExportCount => InterfaceStrings.LogicTypeExportCount, 
			LogicType.ImportCount => InterfaceStrings.LogicTypeImportCount, 
			LogicType.PowerGeneration => InterfaceStrings.LogicTypePowerGeneration, 
			LogicType.TotalMoles => InterfaceStrings.LogicTypeTotalMoles, 
			LogicType.Volume => InterfaceStrings.LogicTypeVolume, 
			LogicType.Plant => InterfaceStrings.LogicTypePlant, 
			LogicType.Harvest => InterfaceStrings.LogicTypeHarvest, 
			LogicType.Output => InterfaceStrings.LogicTypeOutput, 
			LogicType.PressureSetting => InterfaceStrings.LogicTypePressureSetting, 
			LogicType.TemperatureSetting => InterfaceStrings.LogicTypeTemperatureSetting, 
			LogicType.TemperatureExternal => InterfaceStrings.LogicTypeTemperatureExternal, 
			LogicType.Filtration => InterfaceStrings.LogicTypeFiltration, 
			LogicType.AirRelease => InterfaceStrings.LogicTypeAirRelease, 
			LogicType.PositionX => InterfaceStrings.LogicTypePositionX, 
			LogicType.PositionY => InterfaceStrings.LogicTypePositionY, 
			LogicType.PositionZ => InterfaceStrings.LogicTypePositionZ, 
			LogicType.VelocityMagnitude => InterfaceStrings.LogicTypeVelocityMagnitude, 
			LogicType.VelocityRelativeX => InterfaceStrings.LogicTypeVelocityRelativeX, 
			LogicType.VelocityRelativeY => InterfaceStrings.LogicTypeVelocityRelativeY, 
			LogicType.VelocityRelativeZ => InterfaceStrings.LogicTypeVelocityRelativeZ, 
			LogicType.CelestialHash => GameStrings.LogicDescriptionCelestialHash.DisplayString, 
			LogicType.PrefabHash => InterfaceStrings.LogicTypePrefabHash, 
			LogicType.ForceWrite => InterfaceStrings.LogicTypeForceWrite, 
			LogicType.SignalID => InterfaceStrings.LogicTypeSignalID, 
			LogicType.SignalStrength => InterfaceStrings.LogicTypeSignalStrength, 
			LogicType.TargetX => InterfaceStrings.LogicTypeTargetX, 
			LogicType.TargetY => InterfaceStrings.LogicTypeTargetY, 
			LogicType.TargetZ => InterfaceStrings.LogicTypeTargetZ, 
			LogicType.SettingInput => InterfaceStrings.LogicTypeSettingInput, 
			LogicType.SettingOutput => InterfaceStrings.LogicTypeSettingOutput, 
			LogicType.CurrentResearchPodType => InterfaceStrings.ResearchPodTypeMessage, 
			LogicType.ManualResearchRequiredPod => InterfaceStrings.GetManualResearchPodsRequired, 
			LogicType.MineablesInVicinity => InterfaceStrings.GetMineablesInVicinity, 
			LogicType.MineablesInQueue => InterfaceStrings.GetRobotMineablesInQueue, 
			LogicType.NextWeatherEventTime => InterfaceStrings.GetNextWeatherEventTime, 
			LogicType.NextWeatherHash => GameStrings.NextWeatherHashDescription, 
			LogicType.ReturnFuelCost => InterfaceStrings.GetFuelInTankRemaining, 
			LogicType.Fuel => InterfaceStrings.GetFuelReturnCost, 
			LogicType.CollectableGoods => InterfaceStrings.GetCollectableGoods, 
			LogicType.Time => InterfaceStrings.LogicTypeTime, 
			LogicType.Bpm => InterfaceStrings.LogicTypeBpm, 
			LogicType.EnvironmentEfficiency => InterfaceStrings.LogicTypeEnvironmentEfficiency, 
			LogicType.WorkingGasEfficiency => InterfaceStrings.LogicTypeWorkingGasEfficiency, 
			LogicType.PressureInput => InterfaceStrings.LogicTypePressureInput, 
			LogicType.TemperatureInput => InterfaceStrings.LogicTypeTemperatureInput, 
			LogicType.RatioOxygenInput => InterfaceStrings.LogicTypeRatioOxygenInput, 
			LogicType.RatioCarbonDioxideInput => InterfaceStrings.LogicTypeRatioCarbonDioxideInput, 
			LogicType.RatioNitrogenInput => InterfaceStrings.LogicTypeRatioNitrogenInput, 
			LogicType.RatioPollutantInput => InterfaceStrings.LogicTypeRatioPollutantInput, 
			LogicType.RatioMethaneInput => InterfaceStrings.LogicTypeRatioMethaneInput, 
			LogicType.RatioWaterInput => InterfaceStrings.LogicTypeRatioWaterInput, 
			LogicType.RatioNitrousOxideInput => InterfaceStrings.LogicTypeRatioNitrousOxideInput, 
			LogicType.RatioLiquidNitrogenInput => InterfaceStrings.LogicTypeRatioLiquidNitrogenInput, 
			LogicType.TotalMolesInput => InterfaceStrings.LogicTypeTotalMolesInput, 
			LogicType.PressureInput2 => InterfaceStrings.LogicTypePressureInput2, 
			LogicType.TemperatureInput2 => InterfaceStrings.LogicTypeTemperatureInput2, 
			LogicType.RatioOxygenInput2 => InterfaceStrings.LogicTypeRatioOxygenInput2, 
			LogicType.RatioCarbonDioxideInput2 => InterfaceStrings.LogicTypeRatioCarbonDioxideInput2, 
			LogicType.RatioNitrogenInput2 => InterfaceStrings.LogicTypeRatioNitrogenInput2, 
			LogicType.RatioPollutantInput2 => InterfaceStrings.LogicTypeRatioPollutantInput2, 
			LogicType.RatioMethaneInput2 => InterfaceStrings.LogicTypeRatioMethaneInput2, 
			LogicType.RatioWaterInput2 => InterfaceStrings.LogicTypeRatioWaterInput2, 
			LogicType.RatioNitrousOxideInput2 => InterfaceStrings.LogicTypeRatioNitrousOxideInput2, 
			LogicType.RatioLiquidNitrogenInput2 => InterfaceStrings.LogicTypeRatioLiquidNitrogenInput2, 
			LogicType.TotalMolesInput2 => InterfaceStrings.LogicTypeTotalMolesInput2, 
			LogicType.PressureOutput => InterfaceStrings.LogicTypePressureOutput, 
			LogicType.TemperatureOutput => InterfaceStrings.LogicTypeTemperatureOutput, 
			LogicType.RatioOxygenOutput => InterfaceStrings.LogicTypeRatioOxygenOutput, 
			LogicType.RatioCarbonDioxideOutput => InterfaceStrings.LogicTypeRatioCarbonDioxideOutput, 
			LogicType.RatioNitrogenOutput => InterfaceStrings.LogicTypeRatioNitrogenOutput, 
			LogicType.RatioPollutantOutput => InterfaceStrings.LogicTypeRatioPollutantOutput, 
			LogicType.RatioMethaneOutput => InterfaceStrings.LogicTypeRatioMethaneOutput, 
			LogicType.RatioWaterOutput => InterfaceStrings.LogicTypeRatioWaterOutput, 
			LogicType.RatioNitrousOxideOutput => InterfaceStrings.LogicTypeRatioNitrousOxideOutput, 
			LogicType.RatioLiquidNitrogenOutput => InterfaceStrings.LogicTypeRatioLiquidNitrogenOutput, 
			LogicType.TotalMolesOutput => InterfaceStrings.LogicTypeTotalMolesOutput, 
			LogicType.PressureOutput2 => InterfaceStrings.LogicTypePressureOutput2, 
			LogicType.TemperatureOutput2 => InterfaceStrings.LogicTypeTemperatureOutput2, 
			LogicType.RatioOxygenOutput2 => InterfaceStrings.LogicTypeRatioOxygenOutput2, 
			LogicType.RatioCarbonDioxideOutput2 => InterfaceStrings.LogicTypeRatioCarbonDioxideOutput2, 
			LogicType.RatioNitrogenOutput2 => InterfaceStrings.LogicTypeRatioNitrogenOutput2, 
			LogicType.RatioPollutantOutput2 => InterfaceStrings.LogicTypeRatioPollutantOutput2, 
			LogicType.RatioMethaneOutput2 => InterfaceStrings.LogicTypeRatioMethaneOutput2, 
			LogicType.RatioWaterOutput2 => InterfaceStrings.LogicTypeRatioWaterOutput2, 
			LogicType.RatioNitrousOxideOutput2 => InterfaceStrings.LogicTypeRatioNitrousOxideOutput2, 
			LogicType.RatioLiquidNitrogenOutput2 => InterfaceStrings.LogicTypeRatioLiquidNitrogenOutput2, 
			LogicType.TotalMolesOutput2 => InterfaceStrings.LogicTypeTotalMolesOutput2, 
			LogicType.CombustionInput => InterfaceStrings.LogicTypeCombustionInput, 
			LogicType.CombustionInput2 => InterfaceStrings.LogicTypeCombustionInput2, 
			LogicType.CombustionOutput => InterfaceStrings.LogicTypeCombustionOutput, 
			LogicType.CombustionOutput2 => InterfaceStrings.LogicTypeCombustionOutput2, 
			LogicType.OperationalTemperatureEfficiency => InterfaceStrings.LogicTypeOperationalTemperatureEfficiency, 
			LogicType.TemperatureDifferentialEfficiency => InterfaceStrings.LogicTypeTemperatureDifferentialEfficiency, 
			LogicType.PressureEfficiency => InterfaceStrings.LogicTypePressureEfficiency, 
			LogicType.CombustionLimiter => InterfaceStrings.LogicTypeCombustionLimiter, 
			LogicType.Throttle => InterfaceStrings.LogicTypeThrottle, 
			LogicType.Rpm => InterfaceStrings.LogicTypeRpm, 
			LogicType.Stress => InterfaceStrings.LogicTypeStress, 
			LogicType.InterrogationProgress => InterfaceStrings.LogicTypeInterrogationProgress, 
			LogicType.TargetPadIndex => InterfaceStrings.LogicTypeTargetPadIndex, 
			LogicType.SizeX => InterfaceStrings.LogicTypeSizeX, 
			LogicType.SizeY => InterfaceStrings.LogicTypeSizeY, 
			LogicType.SizeZ => InterfaceStrings.LogicTypeSizeZ, 
			LogicType.MinimumWattsToContact => InterfaceStrings.LogicTypeMinWattsToContact, 
			LogicType.WattsReachingContact => InterfaceStrings.LogicTypeWattsReachingContact, 
			LogicType.LineNumber => InterfaceStrings.LogicTypeLineNumber, 
			LogicType.Channel0 => InterfaceStrings.LogicTypeChannel, 
			LogicType.Channel1 => InterfaceStrings.LogicTypeChannel, 
			LogicType.Channel2 => InterfaceStrings.LogicTypeChannel, 
			LogicType.Channel3 => InterfaceStrings.LogicTypeChannel, 
			LogicType.Channel4 => InterfaceStrings.LogicTypeChannel, 
			LogicType.Channel5 => InterfaceStrings.LogicTypeChannel, 
			LogicType.Channel6 => InterfaceStrings.LogicTypeChannel, 
			LogicType.Channel7 => InterfaceStrings.LogicTypeChannel, 
			LogicType.Flush => InterfaceStrings.LogicTypeFlush, 
			LogicType.NameHash => GameStrings.LogicDescriptionNameHash.DisplayString, 
			LogicType.StackSize => GameStrings.LogicDescriptionStackSize.DisplayString, 
			LogicType.SoundAlert => InterfaceStrings.LogicTypeSoundAlert, 
			LogicType.VolumeOfLiquid => InterfaceStrings.LogicTypeVolumeOfLiquid, 
			LogicType.RatioLiquidOxygen => InterfaceStrings.LogicTypeRatioLiquidOxygen, 
			LogicType.RatioLiquidOxygenInput => InterfaceStrings.LogicTypeRatioLiquidOxygenInput, 
			LogicType.RatioLiquidOxygenInput2 => InterfaceStrings.LogicTypeRatioLiquidOxygenInput2, 
			LogicType.RatioLiquidOxygenOutput => InterfaceStrings.LogicTypeRatioLiquidOxygenOutput, 
			LogicType.RatioLiquidOxygenOutput2 => InterfaceStrings.LogicTypeRatioLiquidOxygenOutput2, 
			LogicType.RatioLiquidMethane => InterfaceStrings.LogicTypeRatioLiquidMethane, 
			LogicType.RatioLiquidMethaneInput => InterfaceStrings.LogicTypeRatioLiquidMethaneInput, 
			LogicType.RatioLiquidMethaneInput2 => InterfaceStrings.LogicTypeRatioLiquidMethaneInput2, 
			LogicType.RatioLiquidMethaneOutput => InterfaceStrings.LogicTypeRatioLiquidMethaneOutput, 
			LogicType.RatioLiquidMethaneOutput2 => InterfaceStrings.LogicTypeRatioLiquidMethaneOutput2, 
			LogicType.RatioSteam => InterfaceStrings.LogicTypeRatioSteam, 
			LogicType.RatioSteamInput => InterfaceStrings.LogicTypeRatioSteamInput, 
			LogicType.RatioSteamInput2 => InterfaceStrings.LogicTypeRatioSteamInput2, 
			LogicType.RatioSteamOutput => InterfaceStrings.LogicTypeRatioSteamOutput, 
			LogicType.RatioSteamOutput2 => InterfaceStrings.LogicTypeRatioSteamOutput2, 
			LogicType.ContactTypeId => InterfaceStrings.LogicTypeContactTypeId, 
			LogicType.RatioLiquidCarbonDioxide => InterfaceStrings.LogicTypeRatioLiquidCarbonDioxide, 
			LogicType.RatioLiquidCarbonDioxideInput => InterfaceStrings.LogicTypeRatioLiquidCarbonDioxideInput, 
			LogicType.RatioLiquidCarbonDioxideInput2 => InterfaceStrings.LogicTypeRatioLiquidCarbonDioxideInput2, 
			LogicType.RatioLiquidCarbonDioxideOutput => InterfaceStrings.LogicTypeRatioLiquidCarbonDioxideOutput, 
			LogicType.RatioLiquidCarbonDioxideOutput2 => InterfaceStrings.LogicTypeRatioLiquidCarbonDioxideOutput2, 
			LogicType.RatioLiquidPollutant => InterfaceStrings.LogicTypeRatioLiquidPollutant, 
			LogicType.RatioLiquidPollutantInput => InterfaceStrings.LogicTypeRatioLiquidPollutantInput, 
			LogicType.RatioLiquidPollutantInput2 => InterfaceStrings.LogicTypeRatioLiquidPollutantInput2, 
			LogicType.RatioLiquidPollutantOutput => InterfaceStrings.LogicTypeRatioLiquidPollutantOutput, 
			LogicType.RatioLiquidPollutantOutput2 => InterfaceStrings.LogicTypeRatioLiquidPollutantOutput2, 
			LogicType.RatioLiquidNitrousOxide => InterfaceStrings.LogicTypeRatioLiquidNitrousOxide, 
			LogicType.RatioLiquidNitrousOxideInput => InterfaceStrings.LogicTypeRatioLiquidNitrousOxideInput, 
			LogicType.RatioLiquidNitrousOxideInput2 => InterfaceStrings.LogicTypeRatioLiquidNitrousOxideInput2, 
			LogicType.RatioLiquidNitrousOxideOutput => InterfaceStrings.LogicTypeRatioLiquidNitrousOxideOutput, 
			LogicType.RatioLiquidNitrousOxideOutput2 => InterfaceStrings.LogicTypeRatioLiquidNitrousOxideOutput2, 
			LogicType.Progress => InterfaceStrings.LogicTypeProgress, 
			LogicType.Acceleration => InterfaceStrings.LogicTypeAcceleration, 
			LogicType.AutoShutOff => InterfaceStrings.LogicTypeAutoShutOff, 
			LogicType.Mass => InterfaceStrings.LogicTypeMass, 
			LogicType.DryMass => InterfaceStrings.LogicTypeDryMass, 
			LogicType.Thrust => InterfaceStrings.LogicTypeThrust, 
			LogicType.Weight => InterfaceStrings.LogicTypeWeight, 
			LogicType.ThrustToWeight => InterfaceStrings.LogicTypeThrustToWeight, 
			LogicType.TimeToDestination => InterfaceStrings.LogicTypeTimeToDestination, 
			LogicType.BurnTimeRemaining => InterfaceStrings.LogicTypeBurnTimeRemaining, 
			LogicType.AutoLand => InterfaceStrings.LogicTypeAutoLand, 
			LogicType.RatioHydrogen => InterfaceStrings.LogicTypeRatioHydrogen, 
			LogicType.RatioLiquidHydrogen => InterfaceStrings.LogicTypeRatioLiquidHydrogen, 
			LogicType.BestContactFilter => GameStrings.LogicDescriptionBestContactFilter, 
			LogicType.RatioPollutedWater => InterfaceStrings.LogicTypeRatioPollutedWater, 
			LogicType.TargetSlotIndex => GameStrings.LogicDescriptionTargetSlotIndex, 
			LogicType.TargetPrefabHash => GameStrings.LogicDescriptionTargetPrefabHash, 
			LogicType.Extended => GameStrings.LogicDescriptionExtended, 
			LogicType.ContactSlotIndex => InterfaceStrings.LogicTypeContactSlotIndex, 
			LogicType.RatioHydrazine => InterfaceStrings.LogicTypeRatioHydrazine, 
			LogicType.RatioLiquidHydrazine => InterfaceStrings.LogicTypeRatioLiquidHydrazine, 
			LogicType.RatioLiquidAlcohol => InterfaceStrings.LogicTypeRatioLiquidAlcohol, 
			LogicType.RatioHelium => InterfaceStrings.LogicTypeRatioHelium, 
			LogicType.RatioLiquidSodiumChloride => InterfaceStrings.LogicTypeRatioLiquidSodiumChloride, 
			LogicType.RatioSilanol => InterfaceStrings.LogicTypeRatioSilanol, 
			LogicType.RatioLiquidSilanol => InterfaceStrings.LogicTypeRatioLiquidSilanol, 
			LogicType.RatioHydrochloricAcid => InterfaceStrings.LogicTypeRatioHydrochloricAcid, 
			LogicType.RatioLiquidHydrochloricAcid => InterfaceStrings.LogicTypeRatioLiquidHydrochloricAcid, 
			LogicType.RatioOzone => InterfaceStrings.LogicTypeRatioOzone, 
			LogicType.RatioLiquidOzone => InterfaceStrings.LogicTypeRatioLiquidOzone, 
			LogicType.RatioHydrogenInput => InterfaceStrings.LogicTypeRatioHydrogenInput, 
			LogicType.RatioHydrogenInput2 => InterfaceStrings.LogicTypeRatioHydrogenInput2, 
			LogicType.RatioHydrogenOutput => InterfaceStrings.LogicTypeRatioHydrogenOutput, 
			LogicType.RatioHydrogenOutput2 => InterfaceStrings.LogicTypeRatioHydrogenOutput2, 
			LogicType.RatioLiquidHydrogenInput => InterfaceStrings.LogicTypeRatioLiquidHydrogenInput, 
			LogicType.RatioLiquidHydrogenInput2 => InterfaceStrings.LogicTypeRatioLiquidHydrogenInput2, 
			LogicType.RatioLiquidHydrogenOutput => InterfaceStrings.LogicTypeRatioLiquidHydrogenOutput, 
			LogicType.RatioLiquidHydrogenOutput2 => InterfaceStrings.LogicTypeRatioLiquidHydrogenOutput2, 
			LogicType.RatioPollutedWaterInput => InterfaceStrings.LogicTypeRatioPollutedWaterInput, 
			LogicType.RatioPollutedWaterInput2 => InterfaceStrings.LogicTypeRatioPollutedWaterInput2, 
			LogicType.RatioPollutedWaterOutput => InterfaceStrings.LogicTypeRatioPollutedWaterOutput, 
			LogicType.RatioPollutedWaterOutput2 => InterfaceStrings.LogicTypeRatioPollutedWaterOutput2, 
			LogicType.RatioHydrazineInput => InterfaceStrings.LogicTypeRatioHydrazineInput, 
			LogicType.RatioHydrazineInput2 => InterfaceStrings.LogicTypeRatioHydrazineInput2, 
			LogicType.RatioHydrazineOutput => InterfaceStrings.LogicTypeRatioHydrazineOutput, 
			LogicType.RatioHydrazineOutput2 => InterfaceStrings.LogicTypeRatioHydrazineOutput2, 
			LogicType.RatioLiquidHydrazineInput => InterfaceStrings.LogicTypeRatioLiquidHydrazineInput, 
			LogicType.RatioLiquidHydrazineInput2 => InterfaceStrings.LogicTypeRatioLiquidHydrazineInput2, 
			LogicType.RatioLiquidHydrazineOutput => InterfaceStrings.LogicTypeRatioLiquidHydrazineOutput, 
			LogicType.RatioLiquidHydrazineOutput2 => InterfaceStrings.LogicTypeRatioLiquidHydrazineOutput2, 
			LogicType.RatioLiquidAlcoholInput => InterfaceStrings.LogicTypeRatioLiquidAlcoholInput, 
			LogicType.RatioLiquidAlcoholInput2 => InterfaceStrings.LogicTypeRatioLiquidAlcoholInput2, 
			LogicType.RatioLiquidAlcoholOutput => InterfaceStrings.LogicTypeRatioLiquidAlcoholOutput, 
			LogicType.RatioLiquidAlcoholOutput2 => InterfaceStrings.LogicTypeRatioLiquidAlcoholOutput2, 
			LogicType.RatioHeliumInput => InterfaceStrings.LogicTypeRatioHeliumInput, 
			LogicType.RatioHeliumInput2 => InterfaceStrings.LogicTypeRatioHeliumInput2, 
			LogicType.RatioHeliumOutput => InterfaceStrings.LogicTypeRatioHeliumOutput, 
			LogicType.RatioHeliumOutput2 => InterfaceStrings.LogicTypeRatioHeliumOutput2, 
			LogicType.RatioLiquidSodiumChlorideInput => InterfaceStrings.LogicTypeRatioLiquidSodiumChlorideInput, 
			LogicType.RatioLiquidSodiumChlorideInput2 => InterfaceStrings.LogicTypeRatioLiquidSodiumChlorideInput2, 
			LogicType.RatioLiquidSodiumChlorideOutput => InterfaceStrings.LogicTypeRatioLiquidSodiumChlorideOutput, 
			LogicType.RatioLiquidSodiumChlorideOutput2 => InterfaceStrings.LogicTypeRatioLiquidSodiumChlorideOutput2, 
			LogicType.RatioSilanolInput => InterfaceStrings.LogicTypeRatioSilanolInput, 
			LogicType.RatioSilanolInput2 => InterfaceStrings.LogicTypeRatioSilanolInput2, 
			LogicType.RatioSilanolOutput => InterfaceStrings.LogicTypeRatioSilanolOutput, 
			LogicType.RatioSilanolOutput2 => InterfaceStrings.LogicTypeRatioSilanolOutput2, 
			LogicType.RatioLiquidSilanolInput => InterfaceStrings.LogicTypeRatioLiquidSilanolInput, 
			LogicType.RatioLiquidSilanolInput2 => InterfaceStrings.LogicTypeRatioLiquidSilanolInput2, 
			LogicType.RatioLiquidSilanolOutput => InterfaceStrings.LogicTypeRatioLiquidSilanolOutput, 
			LogicType.RatioLiquidSilanolOutput2 => InterfaceStrings.LogicTypeRatioLiquidSilanolOutput2, 
			LogicType.RatioHydrochloricAcidInput => InterfaceStrings.LogicTypeRatioHydrochloricAcidInput, 
			LogicType.RatioHydrochloricAcidInput2 => InterfaceStrings.LogicTypeRatioHydrochloricAcidInput2, 
			LogicType.RatioHydrochloricAcidOutput => InterfaceStrings.LogicTypeRatioHydrochloricAcidOutput, 
			LogicType.RatioHydrochloricAcidOutput2 => InterfaceStrings.LogicTypeRatioHydrochloricAcidOutput2, 
			LogicType.RatioLiquidHydrochloricAcidInput => InterfaceStrings.LogicTypeRatioLiquidHydrochloricAcidInput, 
			LogicType.RatioLiquidHydrochloricAcidInput2 => InterfaceStrings.LogicTypeRatioLiquidHydrochloricAcidInput2, 
			LogicType.RatioLiquidHydrochloricAcidOutput => InterfaceStrings.LogicTypeRatioLiquidHydrochloricAcidOutput, 
			LogicType.RatioLiquidHydrochloricAcidOutput2 => InterfaceStrings.LogicTypeRatioLiquidHydrochloricAcidOutput2, 
			LogicType.RatioOzoneInput => InterfaceStrings.LogicTypeRatioOzoneInput, 
			LogicType.RatioOzoneInput2 => InterfaceStrings.LogicTypeRatioOzoneInput2, 
			LogicType.RatioOzoneOutput => InterfaceStrings.LogicTypeRatioOzoneOutput, 
			LogicType.RatioOzoneOutput2 => InterfaceStrings.LogicTypeRatioOzoneOutput2, 
			LogicType.RatioLiquidOzoneInput => InterfaceStrings.LogicTypeRatioLiquidOzoneInput, 
			LogicType.RatioLiquidOzoneInput2 => InterfaceStrings.LogicTypeRatioLiquidOzoneInput2, 
			LogicType.RatioLiquidOzoneOutput => InterfaceStrings.LogicTypeRatioLiquidOzoneOutput, 
			LogicType.RatioLiquidOzoneOutput2 => InterfaceStrings.LogicTypeRatioLiquidOzoneOutput2, 
			LogicType.CurrentNodeType => GameStrings.LogicTypeCurrentNodeType, 
			LogicType.TargetNodeType => GameStrings.LogicTypeTargetNodeType, 
			LogicType.EnergyConvected => GameStrings.LogicTypeEnergyConvected, 
			LogicType.EnergyRadiated => GameStrings.LogicTypeEnergyRadiated, 
			_ => throw new ArgumentOutOfRangeException("logicType", logicType, null), 
		};
	}

	public virtual void Read(RocketBinaryReader reader)
	{
		Device = Thing.Find<Device>(reader.ReadInt64());
	}

	public virtual void Write(RocketBinaryWriter writer)
	{
		writer.WriteInt64((Device != null) ? Device.ReferenceId : 0);
	}

	public static bool IsDeprecated(LogicReagentMode arg)
	{
		return false;
	}

	public static bool IsDeprecated(LogicBatchMethod arg)
	{
		return false;
	}

	public static bool IsDeprecated(SoundAlert arg)
	{
		return false;
	}
}
