using System;
using System.Collections.Generic;
using Assets.Scripts;
using Assets.Scripts.Networking;
using Assets.Scripts.Objects;
using CharacterCustomisation;
using Util.Commands;

namespace UnityEngine.Networking;

public static class MessageFactory
{
	private static readonly Type[] IndexToMessageType = new Type[149]
	{
		typeof(ServerRunCommandMessage),
		typeof(DummyMessage),
		typeof(KitMetaData),
		typeof(OwnerMessage),
		typeof(JoinHeaderMessage),
		typeof(JoinFragmentMessage),
		typeof(PictureFrameMessage),
		typeof(SpawnIncidentRequestToServer),
		typeof(AsteroidVoxelMessage),
		typeof(AsteroidVoxelPaintMessage),
		typeof(IntegratedCircuitHeader),
		typeof(IntegratedCircuitUpdate),
		typeof(SorterFilterDeleteMessage),
		typeof(FabricatorCurrentJobMessage),
		typeof(SetRecipeMessage),
		typeof(FabricatorJobMessage),
		typeof(FabricatorJobDeleteMessage),
		typeof(SorterFilterMessage),
		typeof(LogicStateMessage),
		typeof(LogicActionMessage),
		typeof(LogicConditionMessage),
		typeof(TrackerMessageFromServer),
		typeof(RequestTradeMessage),
		typeof(CommsMotherBoardFilterMessageResult),
		typeof(CommsMotherBoardMessage),
		typeof(CreateStructureMessage),
		typeof(LogicStateAdvanceMessage),
		typeof(ConstructionCreationMessage),
		typeof(EmitSparksMessage),
		typeof(WeldingEffect),
		typeof(AccessChangeFromClient),
		typeof(HumanIdentityMessage),
		typeof(FromServerClientLaunchRocket),
		typeof(AddPrintingComponenetMessage),
		typeof(PlayAudioClipsDataMessage),
		typeof(PlayWorldAudioClipsDataMessage),
		typeof(MoveToSlotMessage),
		typeof(SetLogicFromClient),
		typeof(SetLogicMirrorMessage),
		typeof(SetLogicReagentReaderMessage),
		typeof(SetLogicSlotReaderMessage),
		typeof(SetLogicReaderMessage),
		typeof(SetLogicTransmitterMessage),
		typeof(SetLogicBatchSlotReaderMessage),
		typeof(SetLogicBatchReaderMessage),
		typeof(SetLogicBatchWriterMessage),
		typeof(SetLogicWriterMessage),
		typeof(SetLogicProcessorMessage),
		typeof(ForceKinematicMessage),
		typeof(UseStackableMessage),
		typeof(MergeStackablesMessage),
		typeof(SortContentsMessage),
		typeof(SwapSlotsMessage),
		typeof(MoveToWorldMessage),
		typeof(MoveToWorldPositionMessage),
		typeof(RequestInteractionToServer),
		typeof(DismissHelperHintMessage),
		typeof(RequestUseItemToServer),
		typeof(CallTrader),
		typeof(InterrogateTrader),
		typeof(RequestTrade),
		typeof(TradingResultMessageFromServer),
		typeof(TakeControlMessage),
		typeof(AttackWithMessage),
		typeof(MineAsteroidMessage),
		typeof(AvailableDLCMessage),
		typeof(InteractionMessage),
		typeof(ThingRenameMessage),
		typeof(ThingColorMessage),
		typeof(EntityStateMessage),
		typeof(BlendShapeNuancedMessage),
		typeof(BlendShapeEmoteResetMessage),
		typeof(BlendShapeEmoteMessage),
		typeof(AnimationEmoteMessage),
		typeof(SunOffsetMessage),
		typeof(DecayBaseSetMessage),
		typeof(AddGasCommand),
		typeof(SyncTimeMessage),
		typeof(SyncGameMode),
		typeof(SyncCustomGrowSpeed),
		typeof(ChatMessage),
		typeof(AnnounceMessage),
		typeof(ChatStatusMessage),
		typeof(RespawnMessage),
		typeof(RelinquishControlMessage),
		typeof(DestroyThingRequest),
		typeof(HumanSpawnEffect),
		typeof(PingObjectMessage),
		typeof(PingPositionMessage),
		typeof(PingBoxMessage),
		typeof(SetLogicStepSequencerMessage),
		typeof(SetLogicLfoMessage),
		typeof(MotherBoardCommandMessage),
		typeof(SelectDeviceMessage),
		typeof(SelectRocketMessage),
		typeof(RemoveSpaceMapNodesOfTypeMessage),
		typeof(RemoveSpaceMapNodeMessage),
		typeof(SetReEntryProfileMessage),
		typeof(AbandonRocketMessage),
		typeof(AutoLandRocketMessage),
		typeof(AutoShutOffRocketMessage),
		typeof(SetRocketTargetDestinationMessage),
		typeof(PinDeviceMessage),
		typeof(PinLogicValueMessage),
		typeof(SetTransferTargetMessage),
		typeof(SetRocketModeMessage),
		typeof(SetLogicValueMessage),
		typeof(LinkPylonsMessage),
		typeof(ThingSpawnMessage),
		typeof(SpawnSpawnDataMessage),
		typeof(SpawnDynamicThingMaxStackMessage),
		typeof(SpawnGas),
		typeof(NetworkMessages.Handshake),
		typeof(NetworkMessages.PhysicsUpdateMessage),
		typeof(NetworkMessages.CreateThing),
		typeof(NetworkMessages.VerifyPlayer),
		typeof(NetworkMessages.VerifyPlayerRequest),
		typeof(NetworkMessages.DisconnectClient),
		typeof(NetworkMessages.Interact),
		typeof(NetworkMessages.ThingUpdate),
		typeof(NetworkMessages.ExplodeMessage),
		typeof(NetworkMessages.ExplosionMessage),
		typeof(NetworkMessages.GameStateMessage),
		typeof(NetworkMessages.ClientConnectionMessage),
		typeof(NetworkMessages.CollisionMessage),
		typeof(NetworkMessages.GenerateRoomMessage),
		typeof(NetworkMessages.JetpackStateMessage),
		typeof(NetworkMessages.InteractionSyncMessage),
		typeof(NetworkMessages.ResetManagerMessage),
		typeof(NetworkMessages.GasMixtureMessage),
		typeof(NetworkMessages.AtmosphereDestroyMessage),
		typeof(NetworkMessages.PlayerConnectionMessage),
		typeof(NetworkMessages.SteamServerIdMessage),
		typeof(NetworkMessages.ValidateAuthBlobMessage),
		typeof(NetworkMessages.SpawnIncidentResultFromServer),
		typeof(NetworkMessages.PlayerInfoMessage),
		typeof(NetworkMessages.KickPlayerMessage),
		typeof(NetworkMessages.BanPlayerMessage),
		typeof(NetworkMessages.ClientUpdatePlayerDataMessage),
		typeof(NetworkMessages.ServerNoticeMessage),
		typeof(NetworkMessages.TrackerMessage),
		typeof(NetworkMessages.ExplosiveLinkMessage),
		typeof(NetworkMessages.DisconnectP2PMessage),
		typeof(NetworkMessages.UpdatePauseMessage),
		typeof(NetworkMessages.PreLoadingMessage),
		typeof(NetworkMessages.TravelWorldMessage),
		typeof(NetworkMessages.FireProjectileMessage),
		typeof(NetworkMessages.FromServer.GameMetaData),
		typeof(PlaceCableRunMessage)
	};

	private static readonly Dictionary<Type, byte> MessageTypeToIndex = new Dictionary<Type, byte>
	{
		[typeof(ServerRunCommandMessage)] = 0,
		[typeof(DummyMessage)] = 1,
		[typeof(KitMetaData)] = 2,
		[typeof(OwnerMessage)] = 3,
		[typeof(JoinHeaderMessage)] = 4,
		[typeof(JoinFragmentMessage)] = 5,
		[typeof(PictureFrameMessage)] = 6,
		[typeof(SpawnIncidentRequestToServer)] = 7,
		[typeof(AsteroidVoxelMessage)] = 8,
		[typeof(AsteroidVoxelPaintMessage)] = 9,
		[typeof(IntegratedCircuitHeader)] = 10,
		[typeof(IntegratedCircuitUpdate)] = 11,
		[typeof(SorterFilterDeleteMessage)] = 12,
		[typeof(FabricatorCurrentJobMessage)] = 13,
		[typeof(SetRecipeMessage)] = 14,
		[typeof(FabricatorJobMessage)] = 15,
		[typeof(FabricatorJobDeleteMessage)] = 16,
		[typeof(SorterFilterMessage)] = 17,
		[typeof(LogicStateMessage)] = 18,
		[typeof(LogicActionMessage)] = 19,
		[typeof(LogicConditionMessage)] = 20,
		[typeof(TrackerMessageFromServer)] = 21,
		[typeof(RequestTradeMessage)] = 22,
		[typeof(CommsMotherBoardFilterMessageResult)] = 23,
		[typeof(CommsMotherBoardMessage)] = 24,
		[typeof(CreateStructureMessage)] = 25,
		[typeof(LogicStateAdvanceMessage)] = 26,
		[typeof(ConstructionCreationMessage)] = 27,
		[typeof(EmitSparksMessage)] = 28,
		[typeof(WeldingEffect)] = 29,
		[typeof(AccessChangeFromClient)] = 30,
		[typeof(HumanIdentityMessage)] = 31,
		[typeof(FromServerClientLaunchRocket)] = 32,
		[typeof(AddPrintingComponenetMessage)] = 33,
		[typeof(PlayAudioClipsDataMessage)] = 34,
		[typeof(PlayWorldAudioClipsDataMessage)] = 35,
		[typeof(MoveToSlotMessage)] = 36,
		[typeof(SetLogicFromClient)] = 37,
		[typeof(SetLogicMirrorMessage)] = 38,
		[typeof(SetLogicReagentReaderMessage)] = 39,
		[typeof(SetLogicSlotReaderMessage)] = 40,
		[typeof(SetLogicReaderMessage)] = 41,
		[typeof(SetLogicTransmitterMessage)] = 42,
		[typeof(SetLogicBatchSlotReaderMessage)] = 43,
		[typeof(SetLogicBatchReaderMessage)] = 44,
		[typeof(SetLogicBatchWriterMessage)] = 45,
		[typeof(SetLogicWriterMessage)] = 46,
		[typeof(SetLogicProcessorMessage)] = 47,
		[typeof(ForceKinematicMessage)] = 48,
		[typeof(UseStackableMessage)] = 49,
		[typeof(MergeStackablesMessage)] = 50,
		[typeof(SortContentsMessage)] = 51,
		[typeof(SwapSlotsMessage)] = 52,
		[typeof(MoveToWorldMessage)] = 53,
		[typeof(MoveToWorldPositionMessage)] = 54,
		[typeof(RequestInteractionToServer)] = 55,
		[typeof(DismissHelperHintMessage)] = 56,
		[typeof(RequestUseItemToServer)] = 57,
		[typeof(CallTrader)] = 58,
		[typeof(InterrogateTrader)] = 59,
		[typeof(RequestTrade)] = 60,
		[typeof(TradingResultMessageFromServer)] = 61,
		[typeof(TakeControlMessage)] = 62,
		[typeof(AttackWithMessage)] = 63,
		[typeof(MineAsteroidMessage)] = 64,
		[typeof(AvailableDLCMessage)] = 65,
		[typeof(InteractionMessage)] = 66,
		[typeof(ThingRenameMessage)] = 67,
		[typeof(ThingColorMessage)] = 68,
		[typeof(EntityStateMessage)] = 69,
		[typeof(BlendShapeNuancedMessage)] = 70,
		[typeof(BlendShapeEmoteResetMessage)] = 71,
		[typeof(BlendShapeEmoteMessage)] = 72,
		[typeof(AnimationEmoteMessage)] = 73,
		[typeof(SunOffsetMessage)] = 74,
		[typeof(DecayBaseSetMessage)] = 75,
		[typeof(AddGasCommand)] = 76,
		[typeof(SyncTimeMessage)] = 77,
		[typeof(SyncGameMode)] = 78,
		[typeof(SyncCustomGrowSpeed)] = 79,
		[typeof(ChatMessage)] = 80,
		[typeof(AnnounceMessage)] = 81,
		[typeof(ChatStatusMessage)] = 82,
		[typeof(RespawnMessage)] = 83,
		[typeof(RelinquishControlMessage)] = 84,
		[typeof(DestroyThingRequest)] = 85,
		[typeof(HumanSpawnEffect)] = 86,
		[typeof(PingObjectMessage)] = 87,
		[typeof(PingPositionMessage)] = 88,
		[typeof(PingBoxMessage)] = 89,
		[typeof(SetLogicStepSequencerMessage)] = 90,
		[typeof(SetLogicLfoMessage)] = 91,
		[typeof(MotherBoardCommandMessage)] = 92,
		[typeof(SelectDeviceMessage)] = 93,
		[typeof(SelectRocketMessage)] = 94,
		[typeof(RemoveSpaceMapNodesOfTypeMessage)] = 95,
		[typeof(RemoveSpaceMapNodeMessage)] = 96,
		[typeof(SetReEntryProfileMessage)] = 97,
		[typeof(AbandonRocketMessage)] = 98,
		[typeof(AutoLandRocketMessage)] = 99,
		[typeof(AutoShutOffRocketMessage)] = 100,
		[typeof(SetRocketTargetDestinationMessage)] = 101,
		[typeof(PinDeviceMessage)] = 102,
		[typeof(PinLogicValueMessage)] = 103,
		[typeof(SetTransferTargetMessage)] = 104,
		[typeof(SetRocketModeMessage)] = 105,
		[typeof(SetLogicValueMessage)] = 106,
		[typeof(LinkPylonsMessage)] = 107,
		[typeof(ThingSpawnMessage)] = 108,
		[typeof(SpawnSpawnDataMessage)] = 109,
		[typeof(SpawnDynamicThingMaxStackMessage)] = 110,
		[typeof(SpawnGas)] = 111,
		[typeof(NetworkMessages.Handshake)] = 112,
		[typeof(NetworkMessages.PhysicsUpdateMessage)] = 113,
		[typeof(NetworkMessages.CreateThing)] = 114,
		[typeof(NetworkMessages.VerifyPlayer)] = 115,
		[typeof(NetworkMessages.VerifyPlayerRequest)] = 116,
		[typeof(NetworkMessages.DisconnectClient)] = 117,
		[typeof(NetworkMessages.Interact)] = 118,
		[typeof(NetworkMessages.ThingUpdate)] = 119,
		[typeof(NetworkMessages.ExplodeMessage)] = 120,
		[typeof(NetworkMessages.ExplosionMessage)] = 121,
		[typeof(NetworkMessages.GameStateMessage)] = 122,
		[typeof(NetworkMessages.ClientConnectionMessage)] = 123,
		[typeof(NetworkMessages.CollisionMessage)] = 124,
		[typeof(NetworkMessages.GenerateRoomMessage)] = 125,
		[typeof(NetworkMessages.JetpackStateMessage)] = 126,
		[typeof(NetworkMessages.InteractionSyncMessage)] = 127,
		[typeof(NetworkMessages.ResetManagerMessage)] = 128,
		[typeof(NetworkMessages.GasMixtureMessage)] = 129,
		[typeof(NetworkMessages.AtmosphereDestroyMessage)] = 130,
		[typeof(NetworkMessages.PlayerConnectionMessage)] = 131,
		[typeof(NetworkMessages.SteamServerIdMessage)] = 132,
		[typeof(NetworkMessages.ValidateAuthBlobMessage)] = 133,
		[typeof(NetworkMessages.SpawnIncidentResultFromServer)] = 134,
		[typeof(NetworkMessages.PlayerInfoMessage)] = 135,
		[typeof(NetworkMessages.KickPlayerMessage)] = 136,
		[typeof(NetworkMessages.BanPlayerMessage)] = 137,
		[typeof(NetworkMessages.ClientUpdatePlayerDataMessage)] = 138,
		[typeof(NetworkMessages.ServerNoticeMessage)] = 139,
		[typeof(NetworkMessages.TrackerMessage)] = 140,
		[typeof(NetworkMessages.ExplosiveLinkMessage)] = 141,
		[typeof(NetworkMessages.DisconnectP2PMessage)] = 142,
		[typeof(NetworkMessages.UpdatePauseMessage)] = 143,
		[typeof(NetworkMessages.PreLoadingMessage)] = 144,
		[typeof(NetworkMessages.TravelWorldMessage)] = 145,
		[typeof(NetworkMessages.FireProjectileMessage)] = 146,
		[typeof(NetworkMessages.FromServer.GameMetaData)] = 147,
		[typeof(PlaceCableRunMessage)] = 148
	};

	public static Type GetTypeFromIndex(byte index)
	{
		return IndexToMessageType[index];
	}

	public static byte GetIndexFromType(Type type)
	{
		return MessageTypeToIndex[type];
	}
}
